### PR TITLE
add missing <cstdint> include

### PR DESCRIPTION
**Pull request by trofi**
Upcoming `gcc-13` made `<string>` leaner and does not include `<cstdint>` implicitly anymore. As a result build fails without the change as:

    [  2%] Building CXX object CMakeFiles/wayland-scanner++.dir/scanner/scanner.cpp.o
    scanner/scanner.cpp:378:3: error: 'uint32_t' does not name a type
      378 |   uint32_t width = 0;
          |   ^~~~~~~~

### CODE REVIEW

**Comment by heitbaum** [comment]
Tested as working with gcc-13.1. 👍

@NilsBrause - would it be possible to merge and potentially issue a 1.0.1 release
